import type { Metadata } from "next";
import Navbar from "../components/navbar";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bbhSansHegarty = localFont({
  src: "../public/fonts/BBHSansHegarty-Regular.ttf",
  variable: "--font-bbh-sans-hegarty",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bbhSansHegarty.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
